### ISSUE TITLE
file name misspelling "_namspaces.inc"

### ISSUE THREAD

**Issue by petermacdonald** [SFULibrary/islandora_solution_pack_xml#13]
I'm getting this error message in the Islandora watchdog log:

Plugin islandora_simple_xml_context_condition_namespaces of plugin type context:plugins points to nonexistent file sites/all/modules/islandora_solution_pack_xml/modules/islandora_simple_xml_context/plugins/islandora_simple_xml_context_condition_namespaces.inc for class handler handler

The error appears because the system is looking for a file named "islandora_simple_xml_context_condition_namespaces.inc", but the file on the file system actually has a typo in it. That is, the file name "islandora_simple_xml_context_condition_namspaces.inc" is missing an "e" in "namspaces.inc".

When I correct spelling to "..._namespace.inc" on the file system, the error message goes away.

**Comment by mjordan** [comment]
Hi @petermacdonald, thanks for catching that. I've renamed the file to `islandora_simple_xml_context_condition_namespaces.inc`. Can you pull into 7.x and tell me if the watchdog errors have disappeared?

**Comment by mjordan** [comment]
@petermacdonald I've been doing some work with this module and Context and cannot see any instances of that error, so I'm going to close. Please feel free to reopen if it resurfaces for you.
