### ISSUE TITLE
Viewers aren't invoked as expected

### ISSUE THREAD

**Issue by mjordan** [SFULibrary/islandora_solution_pack_xml#5]
Thanks to @ubermichael for figuring this out.

**Comment by mjordan** [comment]
@ubermichael, this now works as intended. I'd like to do a bit more testing before I merge issue-5 branch into 7.x however.

As discussed earlier, I've moved the Context "integration point" out of the main islandora_solution_pack_xml theme preprocess function into a preprocess function within the islandora_simple_xml_context module, which is where it should have been in the first place.

One change you will need to make to your viewer module is to make the top-level members of its return array from hook_theme() and hook_viewer_info() the same string. For example, in the included viewer, I changed the member of the hook_viewer_info() return array like this:

``` php
/**
 * Implements hook_theme().
 */
function islandora_simple_xml_viewer_theme() {
  return array(
    'islandora_simple_xml_viewer' => array( // <-- Matches islandora_viewer_info item
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-simple-xml-viewer',
      'variables' => array(
        'islandora_object' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_simple_xml_viewer_islandora_viewer_info() {
  return array(
     //   'islandora_simple_xml' => array( <-- bad, get rid of.
    'islandora_simple_xml_viewer' => array( //  <-- good, matches theme item.
      'label' => t('Islandora Simple XML Viewer'),
      'description' => t('A simple XML viewer for Islandora.'),
      'configuration' => 'admin/islandora/islandora_viewers/simple_xml',
      'callback' => 'islandora_simple_xml_viewer_callback',
      'model' => array(
        'islandora:sp_simple_xml'),
      'mimetype' => array('application/xml'),
    ),
  );
}
```

That should be the only change you'll need to make. Now, you should see all of your preprocess functions work as intended when your viewer is the current one according to slandora_simple_xml_context.

**Comment by ubermichael** [comment]
This is great Mark. I'll test it out tomorrow morning.

**Comment by mjordan** [comment]
The issue-5 branch is ready for testing. I created a second, very simple viewer and can invoke the default (no viewer), the Simple XML Viewer, and my markstestviewer from within contexts as expected. Don't forget to clear your cache before testing.

**Comment by mjordan** [comment]
@ubermichael you will also need to increase the weight of the islandora_simple_xml_context to be > 0. In mysql, run

`update system set weight = 1 where name = 'islandora_simple_xml_context';`

I'll add this to the .install file.

**Comment by mjordan** [comment]
Merged into 7.x with 03ad5274f7bdf992ae016ab0e0f576584089518d.

**Comment by ubermichael** [comment]
Updated the ballads_viewer to match. Seems to work for me.

**Comment by mjordan** [comment]
Round 2 testing confirms that! Closing....
